"""
GitHub 연동 툴
실제 GitHub Repository에 PR, Issue 생성

인증 방법:
1. GitHub CLI (gh) - 자동 인증 (권장)
2. GitHub PAT - 환경 변수로 제공
"""

import os
import json
import subprocess
import requests
from typing import Dict, Any, Optional, List
from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field


class CreateGitHubPRInput(BaseModel):
    """Input schema for create_github_pr tool"""
    repo_url: str = Field(
        description="GitHub 저장소 URL (예: https://github.com/qazz92/security-agent-test)"
    )
    branch_name: str = Field(
        default="security-fixes",
        description="PR을 위한 새 브랜치 이름"
    )
    pr_title: str = Field(
        description="PR 제목"
    )
    pr_body: str = Field(
        description="PR 본문 (마크다운)"
    )
    base_branch: str = Field(
        default="main",
        description="베이스 브랜치 (main, master 등)"
    )


class CreateGitHubPRTool(BaseTool):
    """GitHub에 실제 Pull Request를 생성하는 도구"""

    name: str = "create_github_pr"
    description: str = """
    GitHub Pull Request 템플릿 파일을 생성합니다.

    생성되는 파일:
    - /app/results/pr_template_{timestamp}.md
    - PR 제목, 본문, 생성 방법 포함
    - GitHub CLI, Web UI, API 사용 방법 안내

    실제 PR 생성은 사용자가 직접 수행:
    - 옵션 1: GitHub CLI (gh pr create)
    - 옵션 2: GitHub Web UI
    - 옵션 3: GitHub API (curl)
    """
    args_schema: type[BaseModel] = CreateGitHubPRInput

    def _run(
        self,
        repo_url: str,
        pr_title: str,
        pr_body: str,
        branch_name: str = "security-fixes",
        base_branch: str = "main"
    ) -> Dict[str, Any]:
        """
        GitHub PR 템플릿 파일 생성

        Args:
            repo_url: GitHub 저장소 URL
            pr_title: PR 제목
            pr_body: PR 본문
            branch_name: 새 브랜치 이름
            base_branch: 베이스 브랜치

        Returns:
            PR 템플릿 파일 생성 결과
        """
        import datetime

        try:
            # results 디렉토리가 없으면 생성
            results_dir = "/app/results"
            os.makedirs(results_dir, exist_ok=True)

            # 타임스탬프 생성
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

            # PR 템플릿 파일 생성
            pr_file_path = os.path.join(results_dir, f"pr_template_{timestamp}.md")

            # 저장소에서 owner/repo 추출
            repo_path = self._extract_repo_path(repo_url)

            # PR 템플릿 내용 구성
            pr_template = f"""# Pull Request Template

## Repository Information
- **Repository**: {repo_url}
- **Owner/Repo**: {repo_path}
- **Base Branch**: {base_branch}
- **Branch Name**: {branch_name}
- **Generated**: {timestamp}

---

# {pr_title}

{pr_body}

---

## How to Create This PR

### Option 1: Using GitHub CLI (Recommended)
```bash
# Clone the repository
git clone {repo_url}
cd {repo_path.split('/')[-1]}

# Create and switch to the branch
git checkout -b {branch_name}

# Apply your fixes (generated code from security scan)
# ... copy fix files here ...

# Commit changes
git add .
git commit -m "{pr_title}"

# Push to remote
git push -u origin {branch_name}

# Create PR using GitHub CLI
gh pr create \\
  --base {base_branch} \\
  --head {branch_name} \\
  --title "{pr_title}" \\
  --body-file {pr_file_path}
```

### Option 2: Using GitHub Web UI
1. Clone repository: `git clone {repo_url}`
2. Create branch: `git checkout -b {branch_name}`
3. Apply fixes and commit changes
4. Push: `git push -u origin {branch_name}`
5. Go to {repo_url}/pulls
6. Click "New Pull Request"
7. Select base: `{base_branch}` and compare: `{branch_name}`
8. Copy the content below into PR description

### Option 3: Using GitHub API
```bash
# Set your GitHub token
export GITHUB_TOKEN="your_github_token_here"

# Clone and prepare branch
git clone {repo_url}
cd {repo_path.split('/')[-1]}
git checkout -b {branch_name}

# Apply fixes and commit
git add .
git commit -m "{pr_title}"
git push -u origin {branch_name}

# Create PR via API
curl -X POST \\
  -H "Authorization: token $GITHUB_TOKEN" \\
  -H "Accept: application/vnd.github.v3+json" \\
  https://api.github.com/repos/{repo_path}/pulls \\
  -d '{{
    "title": "{pr_title}",
    "body": "See {pr_file_path} for full details",
    "head": "{branch_name}",
    "base": "{base_branch}"
  }}'
```

---

## 🤖 Generated by AI Security Agent Portfolio
"""

            # 파일 저장
            with open(pr_file_path, 'w', encoding='utf-8') as f:
                f.write(pr_template)

            print(f"✅ PR template saved to: {pr_file_path}")

            return {
                "success": True,
                "pr_template_file": pr_file_path,
                "repo_url": repo_url,
                "repo_path": repo_path,
                "base_branch": base_branch,
                "branch_name": branch_name,
                "pr_title": pr_title,
                "message": f"PR template saved to {pr_file_path}. Use GitHub CLI, Web UI, or API to create the actual PR.",
                "instructions": {
                    "github_cli": f"gh pr create --base {base_branch} --head {branch_name} --title \"{pr_title}\" --body-file {pr_file_path}",
                    "web_ui": f"{repo_url}/compare/{base_branch}...{branch_name}?expand=1",
                    "file_location": pr_file_path
                }
            }

        except Exception as e:
            return {
                "success": False,
                "error": f"Failed to create PR template: {str(e)}",
                "message": "An error occurred while creating PR template file"
            }

    def _check_github_cli(self) -> bool:
        """GitHub CLI 사용 가능 여부 확인"""
        try:
            # gh 설치 확인
            subprocess.run(['gh', '--version'], capture_output=True, check=True, timeout=5)

            # 인증 확인
            auth_check = subprocess.run(
                ['gh', 'auth', 'status'],
                capture_output=True,
                text=True,
                timeout=5
            )

            return auth_check.returncode == 0

        except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
            return False

    def _create_pr_with_cli(
        self,
        repo_path: str,
        base_branch: str,
        branch_name: str,
        pr_title: str,
        pr_body: str,
        has_changes: bool
    ) -> Dict[str, Any]:
        """GitHub CLI로 PR 생성"""
        import tempfile

        # PR 본문을 임시 파일로 저장
        with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
            f.write(pr_body)
            body_file = f.name

        try:
            pr_result = subprocess.run(
                [
                    'gh', 'pr', 'create',
                    '--repo', repo_path,
                    '--base', base_branch,
                    '--head', branch_name,
                    '--title', pr_title,
                    '--body-file', body_file
                ],
                capture_output=True,
                text=True,
                timeout=30
            )

            if pr_result.returncode == 0:
                pr_url = pr_result.stdout.strip()
                return {
                    "success": True,
                    "pr_url": pr_url,
                    "branch": branch_name,
                    "base_branch": base_branch,
                    "message": f"Pull Request created successfully: {pr_url}",
                    "commits": 1 if has_changes else 0,
                    "method": "github_cli"
                }
            else:
                return {
                    "success": False,
                    "error": "Failed to create PR with GitHub CLI",
                    "details": pr_result.stderr,
                    "branch_pushed": True,
                    "message": f"Branch '{branch_name}' was pushed but PR creation failed."
                }

        finally:
            os.unlink(body_file)

    def _create_pr_with_api(
        self,
        repo_path: str,
        base_branch: str,
        branch_name: str,
        pr_title: str,
        pr_body: str,
        github_token: str,
        has_changes: bool
    ) -> Dict[str, Any]:
        """GitHub API로 직접 PR 생성"""

        # API endpoint
        api_url = f"https://api.github.com/repos/{repo_path}/pulls"

        # Headers
        headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "SecurityAgent"
        }

        # Request body
        data = {
            "title": pr_title,
            "body": pr_body,
            "head": branch_name,
            "base": base_branch
        }

        try:
            response = requests.post(api_url, headers=headers, json=data, timeout=30)

            if response.status_code == 201:
                pr_data = response.json()
                return {
                    "success": True,
                    "pr_url": pr_data["html_url"],
                    "pr_number": pr_data["number"],
                    "branch": branch_name,
                    "base_branch": base_branch,
                    "message": f"Pull Request created successfully: {pr_data['html_url']}",
                    "commits": 1 if has_changes else 0,
                    "method": "github_api"
                }
            elif response.status_code == 422:
                # PR이 이미 존재하는 경우
                error_data = response.json()
                return {
                    "success": False,
                    "error": "PR already exists or validation failed",
                    "details": error_data.get("message", ""),
                    "errors": error_data.get("errors", []),
                    "branch_pushed": True,
                    "message": "Branch was pushed but PR creation failed. A PR might already exist for this branch."
                }
            else:
                return {
                    "success": False,
                    "error": f"GitHub API returned {response.status_code}",
                    "details": response.text,
                    "branch_pushed": True
                }

        except requests.RequestException as e:
            return {
                "success": False,
                "error": "Failed to create PR via GitHub API",
                "details": str(e),
                "branch_pushed": True
            }

    def _extract_repo_path(self, repo_url: str) -> str:
        """
        GitHub URL에서 owner/repo 추출

        Args:
            repo_url: GitHub 저장소 URL

        Returns:
            owner/repo 형식 문자열
        """
        # https://github.com/qazz92/security-agent-test → qazz92/security-agent-test
        # git@github.com:qazz92/security-agent-test.git → qazz92/security-agent-test

        repo_url = repo_url.rstrip('/')

        if repo_url.startswith('https://github.com/'):
            path = repo_url.replace('https://github.com/', '')
        elif repo_url.startswith('git@github.com:'):
            path = repo_url.replace('git@github.com:', '')
        else:
            # 이미 owner/repo 형식이라고 가정
            return repo_url

        # .git 제거
        path = path.replace('.git', '')

        return path


class CreateGitHubIssueInput(BaseModel):
    """Input schema for create_github_issue tool"""
    repo_url: str = Field(
        description="GitHub 저장소 URL"
    )
    issue_title: str = Field(
        description="Issue 제목"
    )
    issue_body: str = Field(
        description="Issue 본문 (마크다운)"
    )
    labels: Optional[List[str]] = Field(
        default=None,
        description="Issue 라벨 리스트 (예: ['security', 'bug'])"
    )


class CreateGitHubIssueTool(BaseTool):
    """GitHub에 Issue를 생성하는 도구"""

    name: str = "create_github_issue"
    description: str = "GitHub Repository에 Issue를 생성합니다. 보안 취약점 보고 등에 사용."
    args_schema: type[BaseModel] = CreateGitHubIssueInput

    def _run(
        self,
        repo_url: str,
        issue_title: str,
        issue_body: str,
        labels: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        GitHub Issue 생성

        Args:
            repo_url: GitHub 저장소 URL
            issue_title: Issue 제목
            issue_body: Issue 본문
            labels: 라벨 리스트

        Returns:
            Issue 생성 결과
        """
        try:
            # GitHub CLI 확인
            try:
                subprocess.run(['gh', '--version'], capture_output=True, check=True, timeout=5)
            except (FileNotFoundError, subprocess.CalledProcessError):
                return {
                    "success": False,
                    "error": "GitHub CLI (gh) not installed"
                }

            # 저장소 경로 추출
            pr_tool = CreateGitHubPRTool()
            repo_path = pr_tool._extract_repo_path(repo_url)

            # Issue 본문을 임시 파일로 저장
            import tempfile
            with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
                f.write(issue_body)
                body_file = f.name

            try:
                # GitHub CLI로 Issue 생성
                cmd = [
                    'gh', 'issue', 'create',
                    '--repo', repo_path,
                    '--title', issue_title,
                    '--body-file', body_file
                ]

                # 라벨 추가
                if labels:
                    for label in labels:
                        cmd.extend(['--label', label])

                issue_result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=30
                )

                if issue_result.returncode == 0:
                    issue_url = issue_result.stdout.strip()
                    return {
                        "success": True,
                        "issue_url": issue_url,
                        "message": f"Issue created successfully: {issue_url}"
                    }
                else:
                    return {
                        "success": False,
                        "error": "Failed to create issue",
                        "details": issue_result.stderr
                    }

            finally:
                os.unlink(body_file)

        except Exception as e:
            return {
                "success": False,
                "error": f"Unexpected error: {str(e)}"
            }


# Tool instances for backward compatibility
_create_github_pr_tool = CreateGitHubPRTool()
_create_github_issue_tool = CreateGitHubIssueTool()

# CrewAI-compatible tool wrappers
from crewai.tools import tool

@tool("Create GitHub PR")
def create_github_pr(
    repo_url: str,
    pr_title: str,
    pr_body: str,
    branch_name: str = "security-fixes",
    base_branch: str = "main"
) -> dict:
    """GitHub Repository에 Pull Request를 생성합니다. 보안 패치를 위한 브랜치 생성, 커밋, 푸시 및 PR 생성까지 자동으로 처리합니다. GitHub CLI 또는 GITHUB_TOKEN 환경 변수를 통해 인증합니다."""
    return _create_github_pr_tool._run(
        repo_url=repo_url,
        pr_title=pr_title,
        pr_body=pr_body,
        branch_name=branch_name,
        base_branch=base_branch
    )

@tool("Create GitHub Issue")
def create_github_issue(
    repo_url: str,
    issue_title: str,
    issue_body: str,
    labels: Optional[List[str]] = None
) -> dict:
    """GitHub Repository에 Issue를 생성합니다. 보안 취약점 보고나 개선 제안 등을 이슈로 등록할 때 사용합니다. GitHub CLI를 통해 인증합니다."""
    return _create_github_issue_tool._run(
        repo_url=repo_url,
        issue_title=issue_title,
        issue_body=issue_body,
        labels=labels
    )